### ISSUE TITLE
Run labrador standalone without POW on OSX ?

### ISSUE THREAD

**Issue by daslicht** [chrismccord/labrador#24]
I have successfully installed labrador and tried to run it by creating an alias in my bash profile since I don't use pow or ruby to create apps.

```
alias labrador-start="cd $HOME/.labrador && bundle exec rails s -e production -p 7488"
```

When I start the app I get: 

```
daslicht:~ daslicht$ labrador-start
/Library/Ruby/Gems/1.8/gems/bundler-1.3.5/lib/bundler/runtime.rb:216: warning: Insecure world writable dir /Users/daslicht/dart/dart-sdk/bin in PATH, mode 040777
/Library/Ruby/Gems/1.8/gems/bundler-1.3.5/lib/bundler/runtime.rb:216: warning: Insecure world writable dir /Users/daslicht/dart/dart-sdk/bin in PATH, mode 040777
/Library/Ruby/Gems/1.8/gems/bundler-1.3.5/lib/bundler/runtime.rb:216: warning: Insecure world writable dir /Users/daslicht/dart/dart-sdk/bin in PATH, mode 040777
=> Booting WEBrick
=> Rails 3.2.12 application starting in production on http://0.0.0.0:7488
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require': /Users/daslicht/.labrador/app/controllers/application_controller.rb:7: syntax error, unexpected ':', expecting kEND (SyntaxError)
  before_filter :http_authenticate, except: [:unauthorized]
                                           ^
/Users/daslicht/.labrador/app/controllers/application_controller.rb:20: syntax error, unexpected ':', expecting kEND
    render json: { error: error.to_s }
                ^
/Users/daslicht/.labrador/app/controllers/application_controller.rb:20: odd number list for Hash
    render json: { error: error.to_s }
                         ^
/Users/daslicht/.labrador/app/controllers/application_controller.rb:20: syntax error, unexpected '}', expecting kEND
/Users/daslicht/.labrador/app/controllers/application_controller.rb:91: syntax error, unexpected ':', expecting ')'
      adapter: adapter_error.adapter, 
              ^
/Users/daslicht/.labrador/app/controllers/application_controller.rb:92: syntax error, unexpected ':', expecting '='
      app: current_app.name
          ^
/Users/daslicht/.labrador/app/controllers/application_controller.rb:93: syntax error, unexpected ')', expecting kEND
/Users/daslicht/.labrador/app/controllers/application_controller.rb:121: syntax error, unexpected $end, expecting kEND
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:359:in `require_or_load'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:313:in `depend_on'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:225:in `require_dependency'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/railties-3.2.12/lib/rails/engine.rb:439:in `eager_load!'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/railties-3.2.12/lib/rails/engine.rb:438:in `each'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/railties-3.2.12/lib/rails/engine.rb:438:in `eager_load!'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/railties-3.2.12/lib/rails/engine.rb:436:in `each'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/railties-3.2.12/lib/rails/engine.rb:436:in `eager_load!'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/railties-3.2.12/lib/rails/application/finisher.rb:53
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:30:in `run'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:55:in `run_initializers'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:54:in `each'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/railties-3.2.12/lib/rails/application.rb:136:in `initialize!'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in `send'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/daslicht/.labrador/config/environment.rb:5
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from /Users/daslicht/.labrador/config.ru:3
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
    from /Users/daslicht/.labrador/vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
    from /Users/daslicht/.labrador/config.ru:0:in `new'
    from /Users/daslicht/.labrador/config.ru:0
daslicht:.labrador daslicht$ 
```

**Comment by chrismccord** [comment]
It looks like the ruby version being loaded is 1.8. Labrador requires 1.9+. Do you have 1.9 installed?

**Comment by daslicht** [comment]
I apologize, I have no experience with ruby.

**Comment by daslicht** [comment]
I have :  ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]

I try to upgrade it

**Comment by chrismccord** [comment]
Please install `rvm` or `rbenv` to manage your rubies. `rvm` is pretty quick to get setup and and compile a 1.9 ruby. Instructions can be found here https://rvm.io

Let me know if that gets you up and running.

**Comment by daslicht** [comment]
Ok I try that , I just have started installing ruby using homebrew, if that fails I try rvm :)
Thank you ! I keep you posted

**Comment by daslicht** [comment]
After installing Ruby 1.9 with brew I was prompted to add its dir to the PATH.
I tried it by adding this to my .bash_profile:

```
export PATH=$PATH:/usr/local/Cellar/ruby/1.9.3-p374/bin
```

But ruby -v still shows 1.8.7 

Any idea what I miss?

**Comment by daslicht** [comment]
This one helped me : 
https://gist.github.com/zenkay/3237860

Now I try to rebuild labrador

**Comment by daslicht** [comment]
still no luck:
https://gist.github.com/daslicht/9cc1f654d9ddcdf1f151

I trued fixing that path but no success
